name: Auto Version Bump

on:
  pull_request:
    types: [opened]
    branches:
      - main

permissions:
  contents: write

jobs:
  version-bump:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check and bump version
        run: |
          VERSION_FILE="version/version.rb"
          
          # Get main branch version
          git fetch origin main
          MAIN_VERSION=$(git show origin/main:$VERSION_FILE | grep "VERSION = " | sed "s/.*'\(.*\)'.*/\1/")
          
          # Get PR branch version
          PR_VERSION=$(grep "VERSION = " "$VERSION_FILE" | sed "s/.*'\(.*\)'.*/\1/")
          
          echo "Main branch version: $MAIN_VERSION"
          echo "PR branch version: $PR_VERSION"
          
          # Extract patch numbers for comparison
          MAIN_PATCH=$(echo "$MAIN_VERSION" | cut -d. -f3)
          PR_PATCH=$(echo "$PR_VERSION" | cut -d. -f3)
          
          # If PR version is greater than main, skip (already bumped)
          if [ "$PR_PATCH" -gt "$MAIN_PATCH" ]; then
            echo "Version already bumped in PR, skipping"
            exit 0
          fi
          
          # Calculate new version (main + 1)
          MAJOR=$(echo "$MAIN_VERSION" | cut -d. -f1)
          MINOR=$(echo "$MAIN_VERSION" | cut -d. -f2)
          NEW_PATCH=$((MAIN_PATCH + 1))
          NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}"
          
          echo "Bumping to: $NEW_VERSION"
          
          # Update version file
          sed -i "s/VERSION = '.*'/VERSION = '$NEW_VERSION'/" "$VERSION_FILE"
          
          # Commit and push
          git add "$VERSION_FILE"
          git commit -m "Auto-bump version to $NEW_VERSION"
          git push origin HEAD:${{ github.head_ref }}
          
          echo "Version bumped to $NEW_VERSION"

